### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by filinep** [dcaoyuan/nbsbt#2]
Hi,

I have installed nbsbt and nbscala and generated the .classpath_nb files. How do I make netbeans open the project now?

I am using: 
netbeans 7.3
nbscala from master
scala 2.10
sbt 0.12.2
nbsbt 1.0.2

Regards,
Filipe

**Comment by cserepj** [comment]
Crap. #3 as well... For 20 or so years all my source code projects lived under c:\Src... I guess there goes an old habit...
